package com.example.supplierselect;

rule "Avaliar Fornecedor pelo Preco"
when
    $fornecedor : Fornecedor(preco < 1000)
then
    $fornecedor.setPontuacao($fornecedor.getPontuacao() + 1); // Peso 1 para preco
end

rule "Avaliar Fornecedor pela Qualidade"
when
    $fornecedor : Fornecedor(qualidade >= 8)
then
    $fornecedor.setPontuacao($fornecedor.getPontuacao() + 10); // Peso 4 para qualidade
end

rule "Avaliar Fornecedor pelo Prazo de Entrega"
when
    $fornecedor : Fornecedor(prazoEntrega <= 5)
then
    $fornecedor.setPontuacao($fornecedor.getPontuacao() + 5); // Peso 2 para prazos de entrega
end

rule "Avaliar Fornecedor pela Reputacao"
when
    $fornecedor : Fornecedor(reputacao >= 4)
then
    $fornecedor.setPontuacao($fornecedor.getPontuacao() + 3); // Peso 2 para reputacao
end

rule "Avaliar Fornecedor pela Capacidade de Atendimento"
when
    $fornecedor : Fornecedor(capacidade >= 500)
then
    $fornecedor.setPontuacao($fornecedor.getPontuacao() + 7); // Peso 3 para capacidade de atendimento
end
